sudo: required
language: java
jdk: openjdk8
env:
  - DOCKER_COMPOSE_VERSION=3.3
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
script:
  - mvn test -B
  - docker-compose up -d discovery config
  - docker ps
  - docker-compose up -d
after_success:
  - docker-compose down
  - echo "Success passed!"
