server:
  port: ${PORT:8086}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/punchat/config.git
---
spring:
  profiles: registration-first
  cloud:
    consul:
      discovery:
        enabled: true
      host: ${serviceUrlDefaultZone:consul}
      port: ${serviceUrlDefaultPort:8500}