server:
  port: ${port}
spring:
  cloud:
    bus:
      enabled: false
    config:
      server:
        git:
          uri: ${configServerGitUri:https://github.com/punchat/config.git}
---
spring:
  profiles: registration-first
eureka:
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: ${serviceUrlDefaultZone:http://discovery:8761/eureka/}
---
spring:
  profiles: config-monitor
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: ${rabbitmqHost:rabbitmq}
    port: ${rabbitmqPort:5672}
    username: ${rabbitmqUsername:guest}
    password: ${rabbitmqPassword:guest}
