server:
  port: ${port}
spring:
    config:
      server:
        git:
          uri: ${configServerGitUri:https://github.com/punchat/config.git}
---
spring:
  profiles: registration-first
eureka:
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: ${serviceUrlDefaultZone:http://discovery:8761/eureka/}
